M48
; DRILL file KiCad 10.0.0 date 2026-04-08T14:15:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-08T14:15:00+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.245
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X149.0Y-68.072
X155.8Y-68.072
T2
X150.122Y-96.684
X165.772Y-68.25
X169.536Y-81.444
T3
X127.0Y-68.326
X127.0Y-103.886
X169.926Y-68.326
M30
